#!/usr/bin/env Rscript
# The R half of the paired oracle. See tests/pairs.py for the whole design.
#
#     R_LIBS=.Rlib Rscript tools/oracle/run_pairs.R <spec.R> <out.json>
#
# `spec.R` is generated by tests/pairs.py and is never committed: it holds the
# R snippets the pairs declare, each with the parameter vector to evaluate it
# at. This script supplies the environment those snippets run in -- the
# `prelude` -- evaluates them, and writes what came back.
#
# Unlike the generators beside it, this script decides nothing. Which
# expressions exist, at which parameters, to what tolerance, and what they are
# supposed to equal in Python are all questions the registry answers. That is
# the point: one artefact states the pairing, and neither language holds half
# of it.

suppressMessages({
  library(CLVTools)
  library(data.table)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2L) stop("usage: run_pairs.R <spec.R> <out.json>", call. = FALSE)
SPEC <- args[[1]]; OUT <- args[[2]]

# The same reach into CLVTools' internals the fixture generators make, and for
# the same reason: the public interface only reports quantities at the fitted
# optimum, which is far too coarse to pair an expression against.
ns <- asNamespace("CLVTools")
cpp <- function(name) get(name, envir = ns)

# -- Preludes -----------------------------------------------------------------
#
# A prelude is the data a family of snippets is evaluated against, built once
# and shared. It also *declares* what it feeds in: `.inputs` is written to the
# output so the harness can check that the Python side was handed the same
# numbers rather than assuming it.

PRELUDES <- list(
  apparel = function() {
    data("apparelTrans", envir = environment())
    d <- clvdata(apparelTrans, date.format = "ymd", time.unit = "week",
                 estimation.split = 104,
                 name.id = "Id", name.date = "Date", name.price = "Price")
    cbs <- latentAttrition(family = pnbd, data = d, verbose = FALSE)@cbs
    env <- new.env(parent = globalenv())
    env$cpp <- cpp
    env$x <- cbs$x; env$tx <- cbs$t.x; env$Tc <- cbs$T.cal
    env$vN <- rep(1, nrow(cbs))
    env$.inputs <- list(x = cbs$x, t.x = cbs$t.x, T.cal = cbs$T.cal)
    env
  }
)

# Built on demand and cached: a prelude fits a model, and a registry naming the
# same one from thirty pairs should pay for it once.
CACHE <- new.env(parent = emptyenv())
prelude <- function(name) {
  if (is.null(PRELUDES[[name]])) stop(sprintf("no prelude named '%s'", name), call. = FALSE)
  if (is.null(CACHE[[name]])) CACHE[[name]] <- PRELUDES[[name]]()
  CACHE[[name]]
}

# -- JSON out -----------------------------------------------------------------
#
# Hand-rolled, as in generate_fixtures.R, so the fixtures carry no dependency
# beyond base R + data.table. 17 significant digits round-trips a double
# exactly; NaN and Inf are written as the tokens Python's `json` accepts, since
# strict JSON has no spelling for either and a silent `null` would turn a
# genuine overflow into a missing value.

num <- function(v) {
  out <- format(v, digits = 17, trim = TRUE)
  out[is.na(v) & !is.nan(v)] <- "null"
  out[is.nan(v)] <- "NaN"
  out[!is.na(v) & is.infinite(v) & v > 0] <- "Infinity"
  out[!is.na(v) & is.infinite(v) & v < 0] <- "-Infinity"
  out
}
arr <- function(v) paste0("[", paste(num(as.numeric(v)), collapse = ","), "]")
obj <- function(kv) paste0("{", paste(sprintf('"%s": %s', names(kv), unlist(kv)),
                                      collapse = ", "), "}")
qstr <- function(s) sprintf('"%s"', s)

# -- Evaluate -----------------------------------------------------------------

source(SPEC, local = TRUE)   # defines CASES

values <- character(0); names(values) <- character(0)
used <- character(0)
for (case in CASES) {
  env <- prelude(case$prelude)
  used <- union(used, case$prelude)
  # `p` is the parameter vector on the NATURAL scale, in both languages. A
  # snippet that needs the log scale writes log(p), which is exactly the
  # convention the Python side must mirror, said once and visibly.
  local_env <- new.env(parent = env)
  local_env$p <- case$p
  v <- as.numeric(eval(case$expr, envir = local_env))
  values[[paste0(case$id, "@", case$input)]] <- arr(v)
  cat(sprintf("  %-46s n=%-5d\n", paste0(case$id, "@", case$input), length(v)))
}

preludes_out <- setNames(
  lapply(used, function(nm) obj(lapply(prelude(nm)$.inputs, arr))),
  used
)

writeLines(obj(list(
  clvtools.version = qstr(as.character(packageVersion("CLVTools"))),
  r.version        = qstr(R.version.string),
  generated.by     = qstr("tools/oracle/run_pairs.R"),
  preludes         = obj(preludes_out),
  values           = obj(as.list(values))
)), OUT)

cat(sprintf("\n%d cases -> %s\n", length(CASES), OUT))
