#!/usr/bin/env Rscript
# The R half of the paired oracle. See tests/pairs.py for the whole design.
#
#     R_LIBS=.Rlib Rscript tools/oracle/run_pairs.R <spec.R> <out.json>
#
# `spec.R` is generated by tests/pairs.py and is never committed: it holds the
# R snippets the pairs declare, each with the parameter vector to evaluate it
# at. This script supplies the environment those snippets run in -- the
# `prelude` -- evaluates them, and writes what came back.
#
# Unlike the generators beside it, this script decides nothing. Which
# expressions exist, at which parameters, to what tolerance, and what they are
# supposed to equal in Python are all questions the registry answers. That is
# the point: one artefact states the pairing, and neither language holds half
# of it.

suppressMessages({
  library(CLVTools)
  library(data.table)
})

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 2L) stop("usage: run_pairs.R <spec.R> <out.json>", call. = FALSE)
SPEC <- args[[1]]; OUT <- args[[2]]

# The same reach into CLVTools' internals the fixture generators make, and for
# the same reason: the public interface only reports quantities at the fitted
# optimum, which is far too coarse to pair an expression against.
ns <- asNamespace("CLVTools")
cpp <- function(name) get(name, envir = ns)

# -- Preludes -----------------------------------------------------------------
#
# A prelude is the data a family of snippets is evaluated against, built once
# and shared. It also *declares* what it feeds in: `.inputs` is written to the
# output so the harness can check that the Python side was handed the same
# numbers rather than assuming it.

PRELUDES <- list(
  apparel = function() {
    data("apparelTrans", envir = environment())
    d <- clvdata(apparelTrans, date.format = "ymd", time.unit = "week",
                 estimation.split = 104,
                 name.id = "Id", name.date = "Date", name.price = "Price")
    cbs <- latentAttrition(family = pnbd, data = d, verbose = FALSE)@cbs
    env <- new.env(parent = globalenv())
    env$cpp <- cpp
    env$x <- cbs$x; env$tx <- cbs$t.x; env$Tc <- cbs$T.cal
    env$vN <- rep(1, nrow(cbs))
    env$.inputs <- list(x = cbs$x, t.x = cbs$t.x, T.cal = cbs$T.cal)
    env
  },

  # The same 600 customers with S6.4's two covariates on both processes. The
  # design matrices go into `.inputs` one column at a time rather than as
  # matrices: a matrix flattens column-major on the way out and would have to
  # be reshaped on the way in, and a reshape that silently transposes is the
  # kind of error this whole mechanism exists to make impossible.
  apparel_staticcov = function() {
    data("apparelTrans", envir = environment())
    data("apparelStaticCov", envir = environment())
    d <- clvdata(apparelTrans, date.format = "ymd", time.unit = "week",
                 estimation.split = 104,
                 name.id = "Id", name.date = "Date", name.price = "Price")
    sc <- SetStaticCovariates(d, data.cov.life = apparelStaticCov,
                              data.cov.trans = apparelStaticCov,
                              names.cov.life = c("Gender", "Channel"),
                              names.cov.trans = c("Gender", "Channel"))
    fit <- latentAttrition(~ Gender + Channel | Gender + Channel,
                           family = pnbd, data = sc, verbose = FALSE)
    cbs <- fit@cbs
    m.life  <- as.matrix(sc@data.cov.life[,  c("Gender", "Channel"), with = FALSE])
    m.trans <- as.matrix(sc@data.cov.trans[, c("Gender", "Channel"), with = FALSE])
    env <- new.env(parent = globalenv())
    env$cpp <- cpp
    env$x <- cbs$x; env$tx <- cbs$t.x; env$Tc <- cbs$T.cal
    env$vN <- rep(1, nrow(cbs))
    env$mLife <- m.life; env$mTrans <- m.trans
    env$.inputs <- list(
      x = cbs$x, t.x = cbs$t.x, T.cal = cbs$T.cal,
      life.Gender  = m.life[, "Gender"],  life.Channel  = m.life[, "Channel"],
      trans.Gender = m.trans[, "Gender"], trans.Channel = m.trans[, "Channel"]
    )
    env
  },

  # Spending. The Gamma-Gamma is fitted on repeat transactions only, so this
  # CBS is not the one above with a column added: it has fewer customers, the
  # zero-repeaters having no mean spending to speak of.
  apparel_spending = function() {
    data("apparelTrans", envir = environment())
    d <- clvdata(apparelTrans, date.format = "ymd", time.unit = "week",
                 estimation.split = 104,
                 name.id = "Id", name.date = "Date", name.price = "Price")
    fit <- spending(family = gg, data = d, verbose = FALSE)
    cbs <- fit@cbs
    env <- new.env(parent = globalenv())
    env$cpp <- cpp
    env$x <- cbs$x; env$mx <- cbs$Spending
    env$vN <- rep(1, nrow(cbs))
    env$.inputs <- list(x = cbs$x, m.x = cbs$Spending)
    env
  },

  # Time-varying covariates, S6.4.2. The most expensive prelude here and still
  # under six seconds, because of one observation: the walk structures do not
  # depend on the parameters. `latentAttrition` is called with `itnmax = 1`, so
  # the optimiser takes a single step and stops, and what comes back is a
  # well-formed fitted object whose walks are the real ones. The fit this
  # family actually needs takes ten minutes and is the reason `dyncov_fit` is
  # deselected from every ordinary run; none of that is paid here.
  #
  # Parameters reach the prediction entry points by `at()` below, which returns
  # a copy of the fitted object carrying a declared parameter vector. Those
  # functions take a fitted object rather than free parameters, so without this
  # they could only ever be checked at whatever optimum a fit happened to
  # reach -- which is exactly the "one point, and not a chosen one" problem the
  # oracle fixtures were built to escape.
  apparel_dyncov = function() {
    NAMES_COV <- c("High.Season", "Gender", "Channel")
    data("apparelTrans", envir = environment())
    data("apparelDynCov", envir = environment())
    clv <- clvdata(apparelTrans, date.format = "ymd", time.unit = "week",
                   estimation.split = 104,
                   name.id = "Id", name.date = "Date", name.price = "Price")
    dyn <- SetDynamicCovariates(
      clv, data.cov.life = apparelDynCov, data.cov.trans = apparelDynCov,
      names.cov.life = NAMES_COV, names.cov.trans = NAMES_COV,
      name.id = "Id", name.date = "Cov.Date")
    fit <- latentAttrition(
      ~ High.Season + Gender + Channel | High.Season + Gender + Channel,
      family = pnbd, data = dyn, verbose = FALSE,
      optimx.args = list(hessian = FALSE, itnmax = 1))

    args <- cpp("pnbd_dyncov_getLLcallargs_ind")(fit)
    cbs <- fit@cbs

    env <- new.env(parent = globalenv())
    env$cpp <- cpp
    env$fit <- fit
    env$args <- args
    env$x <- cbs$x; env$tx <- cbs$t.x; env$Tc <- cbs$T.cal
    env$vN <- rep(1, nrow(cbs))
    env$endDate <- clv@clv.time@timepoint.holdout.end

    # The likelihood entry points take the walks as loose arguments, so a
    # snippet builds its call by name from `args` plus its own `params`.
    env$llargs <- function(p, extra = list()) {
      a <- args
      a$params <- c(log(p$model), p$life, p$trans)
      utils::modifyList(a, extra)
    }
    # Re-parameterising takes three assignments and a fourth thing that is not
    # obvious. `pnbd_dyncov_palive` does not read the coefficients at all: it
    # reads `@LL.data`, the likelihood intermediates computed once at fit time,
    # so setting the slots alone moves `CET` -- which rebuilds its own alive
    # covariates -- and leaves `PAlive` sitting at the fitted values. The
    # symptom is a pair that disagrees by 90% while the likelihood beside it
    # agrees to 4e-15, and the numbers give it away: `PAlive` came back
    # identical for two different gamma vectors. `pnbd_dyncov_getLLdata` is the
    # recomputation CLVTools does for a given parameter vector, so `at()` does
    # it too and every prediction expression then sees one consistent set.
    env$at <- function(p) {
      f <- fit
      f@prediction.params.model[] <- p$model
      f@prediction.params.life[]  <- p$life
      f@prediction.params.trans[] <- p$trans
      f@LL.data <- cpp("pnbd_dyncov_getLLdata")(f, c(log(p$model), p$life, p$trans))
      f
    }

    # The walk arrays are 130,000 rows across seven tables -- too much to
    # commit as a recording when they are already committed as CSVs and pinned
    # by `tests/test_pnbd_dyncov_walks.py`. What goes in `.inputs` instead is a
    # fingerprint of each: its row count and its column sums. That is not the
    # array, and it is not claimed to be; it is enough that a re-baselined walk
    # fixture which nobody re-recorded shows up here rather than silently
    # changing what the likelihood pairs are evaluated on.
    # `na.rm` and a separate NA count, because zero-repeaters have no real
    # transaction walk and carry NA in the index tables. A plain colSums makes
    # every such column NA, which fingerprints nothing; counting them keeps an
    # NA appearing or disappearing visible in its own right.
    fingerprint <- function(m) {
      m <- as.matrix(m)
      c(NROW(m), colSums(m, na.rm = TRUE), colSums(is.na(m)))
    }
    env$.inputs <- list(
      x = cbs$x, t.x = cbs$t.x, T.cal = cbs$T.cal, d_omega = cbs$d_omega,
      fp.covdata_aux_life   = fingerprint(args$covdata_aux_life),
      fp.covdata_real_life  = fingerprint(args$covdata_real_life),
      fp.covdata_aux_trans  = fingerprint(args$covdata_aux_trans),
      fp.covdata_real_trans = fingerprint(args$covdata_real_trans),
      fp.walkinfo_aux_life  = fingerprint(args$walkinfo_aux_life),
      fp.walkinfo_real_life = fingerprint(args$walkinfo_real_life),
      fp.walkinfo_aux_trans = fingerprint(args$walkinfo_aux_trans),
      fp.walkinfo_real_trans = fingerprint(args$walkinfo_real_trans)
    )
    env
  }
)

# Built on demand and cached: a prelude fits a model, and a registry naming the
# same one from thirty pairs should pay for it once.
CACHE <- new.env(parent = emptyenv())
prelude <- function(name) {
  if (is.null(PRELUDES[[name]])) stop(sprintf("no prelude named '%s'", name), call. = FALSE)
  if (is.null(CACHE[[name]])) CACHE[[name]] <- PRELUDES[[name]]()
  CACHE[[name]]
}

# -- JSON out -----------------------------------------------------------------
#
# Hand-rolled, as in generate_fixtures.R, so the fixtures carry no dependency
# beyond base R + data.table. 17 significant digits round-trips a double
# exactly; NaN and Inf are written as the tokens Python's `json` accepts, since
# strict JSON has no spelling for either and a silent `null` would turn a
# genuine overflow into a missing value.

num <- function(v) {
  out <- format(v, digits = 17, trim = TRUE)
  out[is.na(v) & !is.nan(v)] <- "null"
  out[is.nan(v)] <- "NaN"
  out[!is.na(v) & is.infinite(v) & v > 0] <- "Infinity"
  out[!is.na(v) & is.infinite(v) & v < 0] <- "-Infinity"
  out
}
arr <- function(v) paste0("[", paste(num(as.numeric(v)), collapse = ","), "]")
obj <- function(kv) paste0("{", paste(sprintf('"%s": %s', names(kv), unlist(kv)),
                                      collapse = ", "), "}")
qstr <- function(s) sprintf('"%s"', s)

# -- Evaluate -----------------------------------------------------------------

source(SPEC, local = TRUE)   # defines CASES

values <- character(0); names(values) <- character(0)
used <- character(0)
for (case in CASES) {
  env <- prelude(case$prelude)
  used <- union(used, case$prelude)
  # `p` is the parameter vector on the NATURAL scale, in both languages. A
  # snippet that needs the log scale writes log(p), which is exactly the
  # convention the Python side must mirror, said once and visibly.
  local_env <- new.env(parent = env)
  local_env$p <- case$p
  v <- as.numeric(eval(case$expr, envir = local_env))
  values[[paste0(case$id, "@", case$input)]] <- arr(v)
  cat(sprintf("  %-46s n=%-5d\n", paste0(case$id, "@", case$input), length(v)))
}

preludes_out <- setNames(
  lapply(used, function(nm) obj(lapply(prelude(nm)$.inputs, arr))),
  used
)

writeLines(obj(list(
  clvtools.version = qstr(as.character(packageVersion("CLVTools"))),
  r.version        = qstr(R.version.string),
  generated.by     = qstr("tools/oracle/run_pairs.R"),
  preludes         = obj(preludes_out),
  values           = obj(as.list(values))
)), OUT)

cat(sprintf("\n%d cases -> %s\n", length(CASES), OUT))
