"""Shared fixtures.

``data/`` holds the datasets bundled with the R package CLVTools, exported to
CSV by ``tools/extract_data.R``. ``tests/fixtures/`` holds expectations
generated from that package by ``tools/oracle/generate_fixtures.R``; they are
committed, so the suite runs without R.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
FIXTURES = Path(__file__).resolve().parent / "fixtures"


def fixture_csv(name: str, **kwargs) -> pd.DataFrame:
    """An oracle fixture table. ``Id`` is always read as a string.

    CLVTools keys its customer tables by a character ``Id``; reading it as an
    integer here would silently reorder rows relative to the oracle.
    """
    return pd.read_csv(FIXTURES / f"{name}.csv", dtype={"Id": str}, **kwargs)


def fixture_json(name: str):
    """An oracle fixture of scalars or parameter vectors."""
    return json.loads((FIXTURES / f"{name}.json").read_text())


@pytest.fixture(scope="session")
def apparel_trans() -> pd.DataFrame:
    """The apparel retailer transaction log used throughout the paper."""
    return pd.read_csv(
        DATA / "apparelTrans.csv", dtype={"Id": str}, parse_dates=["Date"]
    )


@pytest.fixture(scope="session")
def apparel_static_cov() -> pd.DataFrame:
    """Gender and acquisition Channel, one row per customer."""
    return pd.read_csv(DATA / "apparelStaticCov.csv", dtype={"Id": str})


@pytest.fixture(scope="session")
def cbs_estimation() -> pd.DataFrame:
    """Oracle ``(x, t_x, T)`` over the 104-week estimation period."""
    return fixture_csv("cbs_estimation")


@pytest.fixture(scope="session")
def cbs_full() -> pd.DataFrame:
    """Oracle ``(x, t_x, T)`` over the whole data, no holdout split."""
    return fixture_csv("cbs_full")


@pytest.fixture(scope="session")
def dyncov_walks():
    """The walk structures for the time-varying covariate model.

    Generated by ``tools/oracle/generate_dyncov_fixtures.R``. Loading them from
    the oracle lets the likelihood be tested before the walk construction is,
    so a failure in one does not mask the other.
    """
    from clvtools.pnbd.dyncov import DyncovWalks

    cbs = fixture_csv("dyncov_cbs")
    info = fixture_csv("dyncov_walkinfo")
    real_trans = fixture_csv("dyncov_walkinfo_real_trans")
    covdata = {
        kind: fixture_csv(f"dyncov_covdata_{kind}").to_numpy(dtype=float)
        for kind in ("aux_life", "real_life", "aux_trans", "real_trans")
    }
    return DyncovWalks(
        ids=pd.Index(cbs["Id"], name="Id"),
        x=cbs["x"].to_numpy(dtype=float),
        t_x=cbs["t.x"].to_numpy(dtype=float),
        T_cal=cbs["T.cal"].to_numpy(dtype=float),
        d_omega=cbs["d_omega"].to_numpy(dtype=float),
        walkinfo_aux_life=info[["aux_life_from", "aux_life_to"]].to_numpy(float),
        walkinfo_real_life=info[["real_life_from", "real_life_to"]].to_numpy(float),
        walkinfo_aux_trans=info[
            ["aux_trans_from", "aux_trans_to", "aux_trans_d1", "aux_trans_tjk"]
        ].to_numpy(float),
        walkinfo_real_trans=real_trans[
            ["walk_from", "walk_to", "d1", "tjk"]
        ].to_numpy(float),
        real_trans_from=info["real_trans_from"].to_numpy(dtype=float),
        real_trans_to=info["real_trans_to"].to_numpy(dtype=float),
        covdata_aux_life=covdata["aux_life"],
        covdata_real_life=covdata["real_life"],
        covdata_aux_trans=covdata["aux_trans"],
        covdata_real_trans=covdata["real_trans"],
    )
