"""Shared fixtures.

``src/clvtools/data/`` holds the datasets bundled with the R package CLVTools,
exported to CSV by ``tools/extract_data.R``. They live inside the package rather
than beside it so that they ship in the wheel; a built wheel that could not load
its own data is one of the README's findings.

``tests/fixtures/`` holds expectations generated from that package by the six
scripts in ``tools/oracle/``; they are committed, so the suite runs without R.
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import pytest

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "src" / "clvtools" / "data"
FIXTURES = Path(__file__).resolve().parent / "fixtures"


def fixture_csv(name: str, **kwargs) -> pd.DataFrame:
    """An oracle fixture table. ``Id`` is always read as a string.

    CLVTools keys its customer tables by a character ``Id``; reading it as an
    integer here would silently reorder rows relative to the oracle.
    """
    return pd.read_csv(FIXTURES / f"{name}.csv", dtype={"Id": str}, **kwargs)


def fixture_json(name: str):
    """An oracle fixture of scalars or parameter vectors."""
    return json.loads((FIXTURES / f"{name}.json").read_text())


#: The time-varying covariate likelihood's parameter grid, shared by
#: ``test_pnbd_dyncov.py`` and ``test_pnbd_dyncov_walks.py`` -- the two halves
#: of what was one module before it outgrew the size limit.
DYNCOV_GRID = json.loads((FIXTURES / "dyncov_ll_grid.json").read_text())
DYNCOV_CASES = list(DYNCOV_GRID["params"])


def dyncov_grid_case(case: str):
    r"""``(r, alpha, s, beta, gamma_life, gamma_trans)`` from a grid entry.

    The stored vector is ``[log r, log alpha, log s, log beta, life..., trans...]``
    -- model parameters on the log scale, covariate parameters natural.
    """
    import numpy as np

    p = np.asarray(DYNCOV_GRID["params"][case], dtype=float)
    r, alpha, s, beta = np.exp(p[:4])
    return r, alpha, s, beta, p[4:7], p[7:10]


def oracle_params(pnbd_fixture: str, gg_fixture: str):
    """The oracle's coefficients, wrapped in the dataclasses ``predict`` expects.

    Shared by ``test_predict.py`` and ``test_newcustomer.py`` since round 5
    split the second out of the first -- the same move item 25 made for
    ``DYNCOV_GRID`` when ``test_pnbd_dyncov.py`` outgrew the module-size limit.
    """
    from clvtools.gg import GgParams
    from clvtools.pnbd.fit import PnbdParams

    pnbd = PnbdParams(
        **fixture_json(pnbd_fixture)["coefficients"],
        log_likelihood=float("nan"), converged=True, n_customers=600,
    )
    gg = GgParams(
        **fixture_json(gg_fixture)["coefficients"],
        log_likelihood=float("nan"), converged=True, n_customers=600,
    )
    return pnbd, gg


@pytest.fixture(scope="session")
def apparel_trans() -> pd.DataFrame:
    """The apparel retailer transaction log used throughout the paper."""
    return pd.read_csv(
        DATA / "apparelTrans.csv", dtype={"Id": str}, parse_dates=["Date"]
    )


@pytest.fixture(scope="session")
def apparel_static_cov() -> pd.DataFrame:
    """Gender and acquisition Channel, one row per customer."""
    return pd.read_csv(DATA / "apparelStaticCov.csv", dtype={"Id": str})


@pytest.fixture(scope="module")
def static_data():
    """S6.4's covariate data object: Gender and Channel on both processes.

    Four test modules had built this identically and privately. Module scope
    rather than session, which is the scope all four used: a fitted object is
    cheap to build from the frames above, and one shared instance per module
    keeps a mutation in one module from reaching another.
    """
    from clvtools import ClvData, ClvDataStaticCov

    return ClvDataStaticCov(
        ClvData(
            pd.read_csv(
                DATA / "apparelTrans.csv", dtype={"Id": str}, parse_dates=["Date"]
            ),
            time_unit="week",
            estimation_split=104,
        ),
        pd.read_csv(DATA / "apparelStaticCov.csv", dtype={"Id": str}),
        names_cov_life=["Gender", "Channel"],
        names_cov_trans=["Gender", "Channel"],
    )


@pytest.fixture(scope="session")
def cbs_estimation() -> pd.DataFrame:
    """Oracle ``(x, t_x, T)`` over the 104-week estimation period."""
    return fixture_csv("cbs_estimation")


@pytest.fixture(scope="session")
def cbs_full() -> pd.DataFrame:
    """Oracle ``(x, t_x, T)`` over the whole data, no holdout split."""
    return fixture_csv("cbs_full")


@pytest.fixture(scope="session")
def dyncov_walks():
    """The walk structures for the time-varying covariate model.

    Generated by ``tools/oracle/generate_dyncov_fixtures.R``. Loading them from
    the oracle lets the likelihood be tested before the walk construction is,
    so a failure in one does not mask the other.
    """
    from clvtools.pnbd.dyncov import DyncovWalks

    cbs = fixture_csv("dyncov_cbs")
    info = fixture_csv("dyncov_walkinfo")
    real_trans = fixture_csv("dyncov_walkinfo_real_trans")
    covdata = {
        kind: fixture_csv(f"dyncov_covdata_{kind}").to_numpy(dtype=float)
        for kind in ("aux_life", "real_life", "aux_trans", "real_trans")
    }
    return DyncovWalks(
        ids=pd.Index(cbs["Id"], name="Id"),
        x=cbs["x"].to_numpy(dtype=float),
        t_x=cbs["t.x"].to_numpy(dtype=float),
        T_cal=cbs["T.cal"].to_numpy(dtype=float),
        d_omega=cbs["d_omega"].to_numpy(dtype=float),
        walkinfo_aux_life=info[["aux_life_from", "aux_life_to"]].to_numpy(float),
        walkinfo_real_life=info[["real_life_from", "real_life_to"]].to_numpy(float),
        walkinfo_aux_trans=info[
            ["aux_trans_from", "aux_trans_to", "aux_trans_d1", "aux_trans_tjk"]
        ].to_numpy(float),
        walkinfo_real_trans=real_trans[
            ["walk_from", "walk_to", "d1", "tjk"]
        ].to_numpy(float),
        real_trans_from=info["real_trans_from"].to_numpy(dtype=float),
        real_trans_to=info["real_trans_to"].to_numpy(dtype=float),
        covdata_aux_life=covdata["aux_life"],
        covdata_real_life=covdata["real_life"],
        covdata_aux_trans=covdata["aux_trans"],
        covdata_real_trans=covdata["real_trans"],
    )


def pytest_addoption(parser) -> None:
    """``--run-dyncov-fit``, the other way to ask for the slow fit by name."""
    parser.addoption(
        "--run-dyncov-fit",
        action="store_true",
        default=False,
        help="run the time-varying covariate MLE (about ten minutes)",
    )


def pytest_collection_modifyitems(config, items) -> None:
    """Deselect ``dyncov_fit`` unless it was asked for.

    This lived in ``addopts`` as ``-m 'not dyncov_fit'``, which a caller's own
    ``-m`` silently replaced: ``pytest -m "not slow"`` collected the
    ten-minute fit, the slowest test here and the clearest thing that phrase
    excludes. Here it composes instead. Asking for it still works two ways --
    ``-m dyncov_fit``, which is what ``.github/workflows/dyncov.yml`` runs, or
    ``--run-dyncov-fit`` -- and both are checked for rather than assumed.
    """
    if config.getoption("--run-dyncov-fit"):
        return
    asked_by_marker = "dyncov_fit" in (config.getoption("-m") or "").replace(
        "not dyncov_fit", ""
    )
    if asked_by_marker:
        return

    deselected = [item for item in items if item.get_closest_marker("dyncov_fit")]
    if deselected:
        config.hook.pytest_deselected(items=deselected)
        items[:] = [item for item in items if item not in deselected]
