"""The paired oracle, run.

Two modes over one registry, as ``tests/pairs.py`` describes:

``pytest``
    replay. The Python side of every pair is evaluated and held to the values
    recorded under ``tests/fixtures/pairs/``. No R, so this runs everywhere the
    rest of the suite does, including ``ci.yml``.

``pytest --oracle-live``
    the differential run. Every R snippet is evaluated in a real R session and
    compared three ways -- Python against live R, the recording against live R,
    and each prelude's inputs against the committed copy the Python side reads.
    The second of those is the gate this repository did not previously have: a
    fixture regenerated by hand, edited to make a test pass, or left behind by
    a CLVTools upgrade is green under replay and red here.

``.github/workflows/oracle.yml`` runs the live mode on a schedule, which is
where "somebody should re-run the generators" stops being a thing anyone has to
remember.
"""

from __future__ import annotations

import sys

import numpy as np
import pairs
import pytest
from conftest import fixture_csv

pytestmark = [pytest.mark.oracle, pytest.mark.pair]

pairs.load_all()
CASES = pairs.cases()

#: ``id@input`` for each, which is also the recording key -- so a failure names
#: the line of the recording to look at.
IDS = [pairs.key(p.id, name) for p, name in CASES]

#: The subset a pair has declared has no value to compare; see `TestUndefined`.
UNDEFINED = [(p, name) for p, name in CASES if not p.defined_at(name)]
UNDEFINED_IDS = [pairs.key(p.id, name) for p, name in UNDEFINED]


@pytest.fixture(scope="session")
def live(request, tmp_path_factory):
    """Every R snippet, evaluated once for the whole session.

    Skips unless ``--oracle-live`` was asked for, and fails rather than skips
    if it was asked for and R is missing: a live run that quietly turns into no
    run at all is the failure mode this whole mechanism exists to remove.
    """
    if not request.config.getoption("--oracle-live"):
        pytest.skip("live R comparison not requested (--oracle-live)")
    if not pairs.r_is_available():
        pytest.fail(
            "--oracle-live needs Rscript and .Rlib/CLVTools; see tools/setup_oracle.sh"
        )
    return pairs.run_r(pairs.registry(), tmp_path_factory.mktemp("pairs"))


class TestReplay:
    """The Python side against the recorded oracle. No R."""

    @pytest.mark.parametrize("pair, input_name", CASES, ids=IDS)
    def test_python_matches_the_recording(self, pair, input_name):
        """Every pair, at every input, to the tolerance it declares."""
        want = pairs.recording(pair.family)["values"][pairs.key(pair.id, input_name)]
        if not pair.defined_at(input_name):
            pytest.skip("undefined here; see TestUndefined")
        got = pairs.evaluate(pair, input_name)
        error = pairs.max_rel_error(got, want)
        assert error <= pair.tol, (
            f"{pairs.key(pair.id, input_name)} ({pair.spec}): "
            f"relative error {error:.3e} exceeds {pair.tol:.0e}"
        )


class TestLive:
    """The same registry against a running R session."""

    @pytest.mark.parametrize("pair, input_name", CASES, ids=IDS)
    def test_python_matches_live_r(self, live, pair, input_name):
        """The differential test the recordings only stand in for."""
        k = pairs.key(pair.id, input_name)
        if not pair.defined_at(input_name):
            pytest.skip("undefined here; see TestUndefined")
        error = pairs.max_rel_error(pairs.evaluate(pair, input_name), live["values"][k])
        assert error <= pair.tol, (
            f"{k} ({pair.spec}): python and live R differ by {error:.3e}, "
            f"tolerance {pair.tol:.0e}"
        )

    @pytest.mark.parametrize("pair, input_name", CASES, ids=IDS)
    def test_the_recording_still_matches_live_r(self, live, pair, input_name):
        """The staleness gate: what was committed is what R still produces.

        Held to :data:`pairs.RECORDING_TOL`, which is 1e-12 and not exact
        equality -- see the constant for why, and for what the first Linux run
        of this job had to say about it. Anything above that bound means the
        recording no longer came from this oracle: a hand-edited fixture, a
        generator changed without being re-run, or a CLVTools upgrade nobody
        re-baselined.
        """
        k = pairs.key(pair.id, input_name)
        recorded = pairs.recording(pair.family)["values"][k]
        drift = pairs.max_rel_error_nan_equal(recorded, live["values"][k])
        assert drift <= pairs.RECORDING_TOL, (
            f"{k}: the committed recording differs from live R by {drift:.3e}, "
            f"above {pairs.RECORDING_TOL:.0e} -- re-record with "
            f"tools/oracle/record_pairs.py, and find out why it drifted"
        )

    def test_both_sides_were_fed_the_same_inputs(self, live):
        """The prelude's vectors equal the committed ones the Python side reads.

        Without this, a pair compares two implementations of an expression over
        two different datasets and calls the agreement a result.
        """
        for name, inputs in live["preludes"].items():
            committed = pairs.prelude_inputs(name)
            for column, values in inputs.items():
                assert np.array_equal(committed[column], np.asarray(values, dtype=float)), (
                    f"prelude {name}: column {column} differs from the committed copy"
                )

    def test_how_far_the_recordings_have_drifted(self, live, record_property):
        """Report the worst drift across every case, so the number is visible.

        The bound this passes under says only that nothing is stale. What a
        reader of a green run wants to know is how much room is left, which on
        a machine unlike the one that recorded is the size of the platform's
        own floating-point disagreement. Recorded as a property so it survives
        in the JUnit output, and printed so it survives in the log.
        """
        worst, where = 0.0, ""
        for pair, input_name in CASES:
            k = pairs.key(pair.id, input_name)
            drift = pairs.max_rel_error_nan_equal(
                pairs.recording(pair.family)["values"][k], live["values"][k]
            )
            if drift > worst:
                worst, where = drift, k
        record_property("max_recording_drift", worst)
        sys.stderr.write(f"\nworst recording drift: {worst:.3e} at {where or 'nothing'}\n")
        assert worst <= pairs.RECORDING_TOL

    def test_the_oracle_is_the_version_the_recording_names(self, live):
        """A CLVTools upgrade is a re-baselining decision, not a surprise."""
        recorded = pairs.recording(pairs.registry()[0].family)
        assert live["clvtools.version"] == recorded["clvtools.version"]


class TestUndefined:
    """The inputs where the quantity does not exist, and the two answers given.

    ``undefined_at`` is not a skip list. A pair that names an input here is
    asserting something specific about both implementations -- that CLVTools
    returns ``NaN`` rather than a number, and that this package refuses rather
    than returning one -- and either half changing is a finding. The Pareto/NBD
    CET at ``s = 1`` is the only case so far.
    """

    @pytest.mark.parametrize("pair, input_name", UNDEFINED, ids=UNDEFINED_IDS)
    def test_the_oracle_returns_nan(self, pair, input_name):
        """CLVTools' answer, as recorded."""
        want = pairs.recording(pair.family)["values"][pairs.key(pair.id, input_name)]
        assert np.all(np.isnan(np.asarray(want, dtype=float))), (
            f"{pairs.key(pair.id, input_name)} is declared undefined, but the oracle "
            f"returned numbers"
        )

    @pytest.mark.parametrize("pair, input_name", UNDEFINED, ids=UNDEFINED_IDS)
    def test_python_refuses_rather_than_returning_nan(self, pair, input_name):
        """Ours. A NaN that propagates into a CLV is worse than a stack trace."""
        with pytest.raises(ValueError, match="undefined"):
            pairs.evaluate(pair, input_name)


class TestRegistry:
    """That the registry and its recordings describe the same set of cases."""

    def test_the_prelude_is_the_data_the_rest_of_the_suite_uses(self):
        """``_prelude_apparel.json`` is ``cbs_estimation.csv``, column for column.

        The pairs read their inputs from the prelude recording and live mode
        checks that against R, which leaves one link unchecked: that the paired
        oracle and the 247 fixture-based checks are talking about the same 600
        customers. This is that link, and it needs no R.

        Not exact, and the reason is worth knowing. ``data.table::fwrite``
        writes doubles at 15 significant digits, so every CSV fixture in this
        repository is a *lossy* copy of what R computed -- 328 of these 600
        ``t.x`` values differ from the exact value in the last bits, by up to
        4.3e-15 relative. ``run_pairs.R`` writes 17, which round-trips a double
        exactly, so the recordings do not lose anything. The consequence is
        that no CSV-backed comparison can honestly assert better than about
        1e-14 on its *inputs*, which is where the suite's tightest tolerances
        already sit; the paired oracle has no such floor.
        """
        cbs = fixture_csv("cbs_estimation")
        recorded = pairs.prelude_inputs("apparel")
        for column in ("x", "t.x", "T.cal"):
            np.testing.assert_allclose(
                recorded[column], cbs[column].to_numpy(float), rtol=1e-14, atol=0
            )

    def test_every_case_has_a_recording(self):
        """A pair added without re-recording fails here rather than at replay."""
        missing = [
            pairs.key(pair.id, name)
            for pair, name in CASES
            if pairs.key(pair.id, name) not in pairs.recording(pair.family)["values"]
        ]
        assert not missing, f"no recorded value for {missing}; run record_pairs.py"

    def test_every_recording_has_a_case(self):
        """And a pair removed leaves no orphaned expectation behind.

        An unused recording is worse than a missing one: it looks like coverage
        and checks nothing.
        """
        registered = set(IDS)
        for family in {pair.family for pair in pairs.registry()}:
            orphans = set(pairs.recording(family)["values"]) - registered
            assert not orphans, f"{family}.json records cases no pair claims: {orphans}"

    def test_every_pair_names_a_spec_item_that_exists(self):
        """House rule: a test cites the ``docs/spec.md`` item it covers.

        Checked against the document rather than merely required to be
        non-empty. A citation nobody resolves is how ``P-01`` came to be
        written here on the first draft, for a spec that has no ``P`` items.
        """
        spec = (pairs.ROOT / "docs" / "spec.md").read_text(encoding="utf-8")
        for pair in pairs.registry():
            assert pair.spec, f"{pair.id} names no spec item"
            assert f"**{pair.spec}**" in spec, (
                f"{pair.id} cites {pair.spec}, which docs/spec.md does not define"
            )

    def test_the_r_side_is_generated_rather_than_written_by_hand(self):
        """The spec handed to R contains every case and nothing else."""
        source = pairs.spec_source(pairs.registry())
        assert source.count("list(id =") == len(CASES)
        for pair in pairs.registry():
            assert pair.r in source
